spring:
  application:
    name: edu-tracker-entity
  datasource:
    url: jdbc:mysql://localhost:3306/edutracker
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true